goto_text: "what do we do?"

items:

- icon: dedicated-development-team.svg
  text: Dedicated Development Team

- icon: software-product-development.svg
  text: Software Product Development

- icon: mobile-application-development.svg
  text: Mobile Application Development

- icon: software-qa-and-testing.svg
  text: Software QA & Testing

- icon: technical-consulting.svg
  text: Technical Consulting

- icon: technical-support.svg
  text: Technical Support